name: Python package

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.7']

    steps:
      - uses: actions/checkout@v2
      - name: Install lxml dependencies
        run: sudo apt install libxml2-dev libxslt-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Cython for lxml installation
        run: pip install Cython
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox
      - name: Run flake8
        run: tox -e flake8
